### PR TITLE
Saving our progress so far to main

### PR DESCRIPTION
**Pull request by KrishLal**

### CODE REVIEW

**Comment by mansooranis** [comment]
Closing this pull request as develop requires restructuring, after refactoring some code we can re-open this pull request.

**Comment by manan3172003** [comment]
agreed

**Comment by KrishLal** [comment]
fair, then the push will happen closer to submit date after we consolidate stuff and have actual UI up and running

**Comment by KrishLal** [comment]
Older code has been refactored so I'm re-opening this request

**Pull request merged**
