### PR TITLE
tests remade and fixed, added qrpage tests

### PR DESCRIPTION
**Pull request by Boredalien248**

### CODE REVIEW

**Comment by Boredalien248** [comment]
@mansooranis if you change anything on the app lmk.

**Comment by mansooranis** [comment]
Already have a PR opened with some changes @Boredalien248

**Comment by Boredalien248** [comment]
aight time to kms

**Comment by Boredalien248** [comment]
k this branch is good to go i checked ur changes and updated my tests.

**Comment by Boredalien248** [comment]
@mansooranis I have alll your changes on my branch u can close ur req

**Review by KrishLal — APPROVED** [review]
lgtm 👍

**Review by mansooranis — APPROVED** [review]
Works Ig 😭

**Pull request merged**
