### PR TITLE
Enhanced Profile QRCode

### PR DESCRIPTION
**Pull request by mansooranis**
Contains merge from other features like:
Cloud storage of images
Map fixes
webapp
Leaderboard fix
QRCode image on homepage fix

### CODE REVIEW

**Comment by manan3172003** [comment]
Doesnt seem to have all those branches yet? are you pushing them or is this final

**Comment by mansooranis** [comment]
> Doesnt seem to have all those branches yet? are you pushing them or is this final

I forgot to push 😅

**Comment by manan3172003** [comment]
nw

**Review by manan3172003 — APPROVED** [review]
nice, everything works just need to implement the thing kaustubh implemented on his branch into the chips, other than that gtg

**Review by KrishLal — APPROVED** [review]
dub acquired

**Pull request merged**
