### PR TITLE
103 editprof

### LINKED ISSUE #103: Feat: Edit Profile

### PR DESCRIPTION
**Pull request by KrishLal**
Added functionality of letting a user edit their profile attributes
fixed up some xmls to look consistent with design
fixed a sign up activity bug, should be consistent now

### CODE REVIEW

**Comment by mansooranis** [comment]
Screenshot 2023-03-20 at 8 20 55 PM
Can we add some field tags above each TextInput here to specify which Text input takes which fields.
For example:
First Name:
TextInput
Last Name
TextInput
Email:
TextInput

**Comment by KrishLal** [comment]
> Screenshot 2023-03-20 at 8 20 55 PM Can we add some field tags above each TextInput here to specify which Text input takes which fields. For example: First Name: TextInput Last Name TextInput Email: TextInput

done, changes are live

**Comment by KrishLal** [comment]
fixed

here ya go 
@mansooranis

**Comment by mansooranis** [comment]
Fixed: Now not able to add multiple same QR codes in the wallet unless debug is true.

**Review by mansooranis — APPROVED** [review]
Looks good and works!

**Review by manan3172003 — APPROVED** [review]
working

**Pull request merged**
