### PR TITLE
40 wallet class

### PR DESCRIPTION
**Pull request by mkhan1107**

### CODE REVIEW

**Review by mansooranis — APPROVED** [review]

**Comment by mansooranis** [comment]
The class QRWallet is commented out and will be un-commented once merged into develop. Since some classes are missing for example QRCode, Player, etc. and this branch does not have any of those. @KrishLal

**Comment by mansooranis** [comment]
Also, ignore the current position of the Folder for this class. It will be refactored once merged.

**Comment by KrishLal** [comment]
@mansooranis @mkhan1107 We'll have to exception handling in firebase operations which is something to note when we work on the class. The getScore function also needs to be renamed to getQRScore.

Other than that it looks good to me.
Would you like me to approve it and merge it right now and change the method name in a later revision or request changes and then merge. @mansooranis

**Comment by mansooranis** [comment]
Let's merge it and then refactor the code later. I think we need to set up an operational workflow to get started on the GUI. @KrishLal

**Comment by KrishLal** [comment]
Sounds good to me @mansooranis.

**Review by KrishLal — APPROVED** [review]

**Pull request merged**
