### PR TITLE
Camera and homepage tests

### PR DESCRIPTION
**Pull request by mansooranis**

### CODE REVIEW

**Comment by Boredalien248** [comment]
checkIfReturnsToHomeOnCancel() doesn't work.

**Review by Boredalien248 — CHANGES_REQUESTED** [review]
checkIfReturnsToHomeOnCancel() doesn't work.

**Comment by mansooranis** [comment]
@Boredalien248 Github CI passes the test cases I think you should maybe do a git checkout and then git pull again.

**Comment by Boredalien248** [comment]
tried it locally after checkout and pull didnt work.

**Comment by Boredalien248** [comment]
added a small fix should work now.

**Review by Boredalien248 — APPROVED** [review]
LGTM

**Review by manan3172003 — APPROVED** [review]
passes on CI so should be correct

**Pull request merged**
